EXESUFFIX=
OBJSUFFIX=.o
SLIBSUFFIX=.a
DYNLIBSUFFIX=.so

CC=clang -Wall -Werror -pedantic -ansi -std=c99
CCLIB=clang -fPIC -Wall -Werror -pedantic -ansi -std=c99
ARCMD=ar rcs
RANLIBCMD=ranlib
SHAREDCC=clang -Wall -Werror -shared
MAKE=gmake
CP=cp
MKDIR=mkdir -p
MKSTAGEARCHIVE=tar -czf packages/libccsv-amd64-freebsd.tar.gz -C stage .
RMDIR=rm -rf
RMFILE=rm
